# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGa38Y3-sA6h3wZd9SyHd164IQ_kNHve
"""

import numpy as np

def needleman_wunsch_linear(seq1, seq2, match=1, mismatch=-1, gap=-4):
    """
    Алгоритм Нидлмана-Вунша с линейным штрафом за гэп
    """
    n, m = len(seq1), len(seq2)
    F = np.zeros((n+1, m+1))

    for i in range(n+1):
        F[i][0] = i * gap
    for j in range(m+1):
        F[0][j] = j * gap

    for i in range(1, n+1):
        for j in range(1, m+1):
            match_score = match if seq1[i-1] == seq2[j-1] else mismatch
            F[i][j] = max(
                F[i-1][j-1] + match_score,
                F[i-1][j] + gap,
                F[i][j-1] + gap
            )

    return F

def needleman_wunsch_affine(seq1, seq2, match=1, mismatch=-1, gap_open=-10, gap_extend=-1):
    """
    Алгоритм Нидлмана-Вунша с аффинным штрафом за гэп
    Использует три матрицы: M (совпадения), X (гэпы в seq1), Y (гэпы в seq2)
    """
    n, m = len(seq1), len(seq2)

    M = np.zeros((n+1, m+1))
    X = np.zeros((n+1, m+1))
    Y = np.zeros((n+1, m+1))

    M[0][0] = 0
    for i in range(1, n+1):
        M[i][0] = -np.inf
        X[i][0] = gap_open + (i-1) * gap_extend
        Y[i][0] = -np.inf
    for j in range(1, m+1):
        M[0][j] = -np.inf
        X[0][j] = -np.inf
        Y[0][j] = gap_open + (j-1) * gap_extend

    for i in range(1, n+1):
        for j in range(1, m+1):
            match_score = match if seq1[i-1] == seq2[j-1] else mismatch
            M[i][j] = max(
                M[i-1][j-1] + match_score,
                X[i-1][j-1] + match_score,
                Y[i-1][j-1] + match_score
            )

            X[i][j] = max(
                M[i-1][j] + gap_open,
                X[i-1][j] + gap_extend,
                Y[i-1][j] + gap_open
            )

            Y[i][j] = max(
                M[i][j-1] + gap_open,
                X[i][j-1] + gap_open,
                Y[i][j-1] + gap_extend
            )

    final_score = max(M[n][m], X[n][m], Y[n][m])

    return M, X, Y, final_score

def traceback_linear(seq1, seq2, F, match=1, mismatch=-1, gap=-4):
    """
    Восстановление выравнивания для линейной модели
    """
    align1, align2 = "", ""
    i, j = len(seq1), len(seq2)

    while i > 0 or j > 0:
        if i > 0 and j > 0:
            match_score = match if seq1[i-1] == seq2[j-1] else mismatch
            if abs(F[i][j] - (F[i-1][j-1] + match_score)) < 1e-10:
                align1 = seq1[i-1] + align1
                align2 = seq2[j-1] + align2
                i -= 1
                j -= 1
                continue

        if i > 0 and abs(F[i][j] - (F[i-1][j] + gap)) < 1e-10:
            align1 = seq1[i-1] + align1
            align2 = "-" + align2
            i -= 1
        else:
            align1 = "-" + align1
            align2 = seq2[j-1] + align2
            j -= 1

    return align1, align2

def traceback_affine(seq1, seq2, M, X, Y, match=1, mismatch=-1, gap_open=-10, gap_extend=-1):
    """
    Восстановление выравнивания для аффинной модели
    """
    align1, align2 = "", ""
    i, j = len(seq1), len(seq2)

    scores = [M[i][j], X[i][j], Y[i][j]]
    max_idx = np.argmax(scores)
    state = ['M', 'X', 'Y'][max_idx]

    while i > 0 or j > 0:
        if state == 'M':
            match_score = match if seq1[i-1] == seq2[j-1] else mismatch
            if abs(M[i][j] - (M[i-1][j-1] + match_score)) < 1e-10:
                state = 'M'
            elif abs(M[i][j] - (X[i-1][j-1] + match_score)) < 1e-10:
                state = 'X'
            else:
                state = 'Y'

            align1 = seq1[i-1] + align1
            align2 = seq2[j-1] + align2
            i -= 1
            j -= 1

        elif state == 'X':
            if abs(X[i][j] - (M[i-1][j] + gap_open)) < 1e-10:
                state = 'M'
            elif abs(X[i][j] - (X[i-1][j] + gap_extend)) < 1e-10:
                state = 'X'
            else:
                state = 'Y'

            align1 = seq1[i-1] + align1
            align2 = "-" + align2
            i -= 1

        else:
            if abs(Y[i][j] - (M[i][j-1] + gap_open)) < 1e-10:
                state = 'M'
            elif abs(Y[i][j] - (X[i][j-1] + gap_open)) < 1e-10:
                state = 'X'
            else:
                state = 'Y'

            align1 = "-" + align1
            align2 = seq2[j-1] + align2
            j -= 1

    return align1, align2


seq1 = "ATGCAGCAGCAGCCA"
seq2 = "ATATAT"

F_linear = needleman_wunsch_linear(seq1, seq2, match=1, mismatch=-1, gap=-4)
print("\nМАТРИЦА ЛИНЕЙНОЙ МОДЕЛИ:")
print(F_linear)

align1_linear, align2_linear = traceback_linear(seq1, seq2, F_linear, match=1, mismatch=-1, gap=-4)
print(f"\nВЫРАВНИВАНИЕ (линейная модель):")
print(f"X: {align1_linear}")
print(f"Y: {align2_linear}")

# Подсчет скора для проверки
score_linear = 0
for a, b in zip(align1_linear, align2_linear):
    if a == '-' or b == '-':
        score_linear += -4
    elif a == b:
        score_linear += 1
    else:
        score_linear += -1
print(f"SCORE: {score_linear}")

M, X, Y, score_affine = needleman_wunsch_affine(seq1, seq2, match=1, mismatch=-1, gap_open=-10, gap_extend=-1)

print("\nМАТРИЦА M (совпадения/несовпадения) для аффинной модели:")
M_print = np.where(M == -np.inf, -999, M)
print(M_print)

align1_affine, align2_affine = traceback_affine(seq1, seq2, M, X, Y, match=1, mismatch=-1, gap_open=-10, gap_extend=-1)
print(f"\nВЫРАВНИВАНИЕ (аффинная модель):")
print(f"X: {align1_affine}")
print(f"Y: {align2_affine}")
print(f"SCORE: {score_affine}")